var sourcesIndex = JSON.parse('{\
"bones_asset":["",[],["asset.rs","cid.rs","handle.rs","io.rs","lib.rs","parse.rs","path.rs","serde.rs","server.rs"]],\
"bones_bevy_renderer":["",[],["convert.rs","lib.rs"]],\
"bones_ecs":["",[["components",[],["iterator.rs","typed.rs","untyped.rs"]]],["bitset.rs","components.rs","entities.rs","error.rs","lib.rs","resources.rs","stage.rs","system.rs","world.rs"]],\
"bones_framework":["",[["input",[["time",[],["stopwatch.rs","timer.rs"]]],["gamepad.rs","keyboard.rs","mouse.rs","time.rs","window.rs"]],["render",[["ui",[["widgets",[],["bordered_button.rs","bordered_frame.rs"]]],["widgets.rs"]]],["audio.rs","camera.rs","color.rs","line.rs","sprite.rs","tilemap.rs","transform.rs","ui.rs"]]],["animation.rs","input.rs","lib.rs","localization.rs","params.rs","render.rs"]],\
"bones_lib":["",[],["lib.rs"]],\
"bones_matchmaker":["",[],["certs.rs","cli.rs","lib.rs","matchmaker.rs","proxy.rs"]],\
"bones_matchmaker_proto":["",[],["lib.rs"]],\
"bones_schema":["",[["alloc",[],["layout.rs","map.rs","resizable.rs","type_set.rs","vec.rs"]]],["alloc.rs","lib.rs","ptr.rs","raw_fns.rs","registry.rs","schema.rs","std_impls.rs"]],\
"bones_schema_macros":["",[],["lib.rs"]],\
"bones_utils":["",[],["collections.rs","default.rs","key_mod.rs","labeled_id.rs","lib.rs","names.rs","ptr.rs"]],\
"bones_utils_macros":["",[],["lib.rs"]],\
"demo_assets_minimal":["",[],["main.rs"]],\
"demo_features":["",[],["main.rs"]],\
"demo_hello_world":["",[],["main.rs"]],\
"quinn_runtime_bevy":["",[],["lib.rs"]],\
"type_ulid":["",[],["lib.rs"]],\
"type_ulid_macros":["",[],["lib.rs"]]\
}');
createSourceSidebar();
