var sourcesIndex = JSON.parse('{\
"bones_asset":["",[],["lib.rs"]],\
"bones_bevy_asset":["",[],["lib.rs"]],\
"bones_bevy_asset_macros":["",[],["lib.rs"]],\
"bones_bevy_renderer":["",[],["lib.rs"]],\
"bones_bevy_utils":["",[],["lib.rs"]],\
"bones_camera_shake":["",[],["lib.rs"]],\
"bones_ecs":["",[["components",[["typed",[],["ops.rs"]]],["iterator.rs","typed.rs","untyped.rs"]]],["bitset.rs","components.rs","entities.rs","error.rs","join.rs","lib.rs","resources.rs","stage.rs","system.rs","ulid.rs","world.rs"]],\
"bones_has_load_progress":["",[],["lib.rs"]],\
"bones_has_load_progress_macros":["",[],["lib.rs"]],\
"bones_input":["",[],["lib.rs"]],\
"bones_lib":["",[],["lib.rs"]],\
"bones_matchmaker":["",[],["certs.rs","cli.rs","lib.rs","matchmaker.rs","proxy.rs"]],\
"bones_matchmaker_proto":["",[],["lib.rs"]],\
"bones_render":["",[],["camera.rs","lib.rs","sprite.rs","tilemap.rs","transform.rs"]],\
"quinn_runtime_bevy":["",[],["lib.rs"]],\
"type_ulid":["",[],["lib.rs"]],\
"type_ulid_macros":["",[],["lib.rs"]]\
}');
createSourceSidebar();
