var srcIndex = new Map(JSON.parse('[\
["bones_asset",["",[["server",[],["schema_loader.rs"]]],["asset.rs","cid.rs","handle.rs","io.rs","lib.rs","network_handle.rs","parse.rs","server.rs"]]],\
["bones_bevy_renderer",["",[],["convert.rs","debug.rs","input.rs","lib.rs","render.rs","rumble.rs","storage.rs","ui.rs"]]],\
["bones_ecs",["",[["components",[],["iterator.rs","typed.rs","untyped.rs"]]],["bitset.rs","components.rs","entities.rs","lib.rs","resources.rs","stage.rs","system.rs","world.rs"]]],\
["bones_ecs_macros",["",[],["lib.rs"]]],\
["bones_ecs_macros_core",["",[],["lib.rs"]]],\
["bones_framework",["",[["audio",[],["audio_center.rs","audio_manager.rs"]],["input",[],["gamepad.rs","gilrs.rs","keyboard.rs","mouse.rs","window.rs"]],["networking",[],["input.rs","lan.rs","online.rs","online_lobby.rs","online_matchmaking.rs","proto.rs","random.rs","socket.rs"]],["render",[["ui",[["widgets",[],["bordered_button.rs","bordered_frame.rs"]]],["widgets.rs"]]],["camera.rs","color.rs","line.rs","sprite.rs","tilemap.rs","transform.rs","ui.rs"]],["time",[],["stopwatch.rs","timer.rs"]]],["animation.rs","audio.rs","debug.rs","input.rs","lib.rs","localization.rs","logging.rs","networking.rs","params.rs","render.rs","storage.rs","time.rs","utils.rs"]]],\
["bones_lib",["",[],["lib.rs","time.rs"]]],\
["bones_matchmaker",["",[],["cli.rs","helpers.rs","lib.rs","lobbies.rs","matchmaker.rs","matchmaking.rs"]]],\
["bones_matchmaker_proto",["",[],["lib.rs"]]],\
["bones_schema",["",[["alloc",[],["layout.rs","map.rs","resizable.rs","type_datas.rs","vec.rs"]]],["alloc.rs","lib.rs","ptr.rs","raw_fns.rs","registry.rs","schema.rs","ser_de.rs","std_impls.rs"]]],\
["bones_schema_macros",["",[],["lib.rs"]]],\
["bones_scripting",["",[["lua",[["bindings",[],["assets.rs","components.rs","ecsref.rs","entities.rs","resources.rs","schema.rs","world.rs"]]],["asset.rs","bindings.rs","ext.rs","freeze.rs"]]],["lib.rs","lua.rs"]]],\
["bones_utils",["",[],["collections.rs","default.rs","labeled_id.rs","lib.rs","names.rs","random.rs","ulid.rs"]]],\
["bones_utils_macros",["",[],["lib.rs"]]],\
["demo_asset_packs",["",[],["main.rs"]]],\
["demo_assets_minimal",["",[],["main.rs"]]],\
["demo_features",["",[],["main.rs"]]],\
["demo_hello_world",["",[],["main.rs"]]],\
["demo_scripting",["",[],["main.rs"]]],\
["type_ulid",["",[],["lib.rs"]]],\
["type_ulid_macros",["",[],["lib.rs"]]]\
]'));
createSrcSidebar();
