[package]
authors     = ["The Fish Folk & Spicy Lobster Developers"]
description = "Macros for the type_ulid crate."
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "type_ulid_macros"
repository  = "https://github.com/fishfolk/bones"
version     = "0.2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.43"
quote       = "1.0.21"
syn         = { version = "1.0.100", features = ["extra-traits"] }
ulid        = { version = "1.0.0", default-features = false }
