[package]
name                    = "bones_utils"
description             = "Utilites used throughout the bones_framework."
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true
repository.workspace    = true
documentation.workspace = true
categories.workspace    = true
keywords.workspace      = true

[features]
serde = ["dep:serde", "hashbrown/serde"]

[dependencies]
bones_utils_macros = { version = "0.4", path = "./macros" }
fxhash             = { workspace = true }
hashbrown          = { workspace = true }
instant            = { version = "0.1", features = ["wasm-bindgen"] }
turborand          = "0.10"
ulid               = "1.0"

# Optional
serde = { version = "1.0", optional = true }

# Make sure that the getrandom package, used in `ulid` works on web
# when compiling for WASM.
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
