[package]
name                    = "bones_utils"
description             = "Utilites used throughout the bones_framework."
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true
repository.workspace    = true
documentation.workspace = true
categories.workspace    = true
keywords.workspace      = true

[features]
serde = ["dep:serde", "hashbrown/serde", "ustr/serde"]

[dependencies]
bones_utils_macros = { version = "0.3", path = "./macros" }
smallvec           = "1.11"
fxhash             = "0.2"
hashbrown          = { version = "0.14" }
ulid               = "1.0"
bevy_ptr           = "0.11.0"
parking_lot        = "0.12"
serde              = { version = "1.0", optional = true }
maybe-owned        = "0.3"
branches           = "0.1"
ustr               = "0.10.0"
