[package]
name                    = "bones_utils_macros"
description             = "Macros used in bones_utils."
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true
repository.workspace    = true
documentation.workspace = true
categories.workspace    = true
keywords.workspace      = true

[lib]
proc-macro = true

[dependencies]
quote  = "1.0"
venial = "0.5"
proc-macro2 = "1"
