name: Lint commit message
on:
  push:
    branches:
      - staging
      - trying

jobs:
  commitlint:
    name: Lint commit message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: wagoid/commitlint-github-action@v5
        with:
          commitDepth: 1
