name: ⏮️ Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  merge_group:

jobs:
  main:
    name: 🕵 Validate Conventional PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        name: 🔎 Validate Conventional PR Title
        if: github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
