name: 🚀 Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      # This is to work around this bug in release-plz: https://github.com/MarcoIeni/release-plz/discussions/1203
      # The fix for now is to make sure the previously used rust version is installed before
      # running release-plz.
      - name: Install Previously Supported Rust Version
        run: rustup toolchain add 1.73

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
